### ISSUE TITLE
Instagram link is broken.

### ISSUE THREAD

**Issue by akashshuklacs** [akashgiricse/akashgiricse.github.io#3]
Redirected to broken link when clicking Instagram icon in follow me section.

**To Reproduce**
1. Go to https://akashgiri.com/#section-around-the-web
2. Click on 'Instagram'

**Expected behavior**
Your Instagram should be visible.

**Screenshots**
<img width="1041" alt="Screenshot 2022-09-02 at 2 29 35 PM" src="https://user-images.githubusercontent.com/15183542/188104171-501466c5-a7d4-448b-8481-b1520b19ced8.png">

**Desktop (please complete the following information):**
 - OS: Mac OS Mojave
 - Browser: Saferi
 - Version: 15.6.1

**Solution**
Pls create Instagram account to fix the issue. :D

**Comment by akashshuklacs** [comment]
Any updates on this one?

**Comment by akashgiricse** [comment]
Removed IG link. Thanks.
